#!/usr/bin/bash

PKG_REPO=neovim/neovim
PKG_REGEX=^nvim-linux64.tar.gz$

if [[ -f "info.json" ]]; then
    INFO=$(cat info.json)
else
    INFO=$(get_latest_github_package_info "${PKG_REPO}" "${PKG_REGEX}")
fi

PKG_DOWNLOAD_URL=$(echo "$INFO" | jq ".browser_download_url" | sed 's/"//g')
PKG_NAME=$(echo "$INFO" | jq ".name" | sed 's/"//g' | awk -F '-' '{ print $1 }')
PKG_VERSION=0   # No version information that is easily obtainable

cat << EOF
{
"name" : "$PKG_NAME",
"version" : "$PKG_VERSION",
"download_url" : "$PKG_DOWNLOAD_URL"
}
EOF
